# Default active profile
spring.profiles.active=dev

# Common configurations
server.port=8080
spring.application.name=portfolio-api

# Swagger UI
springdoc.swagger-ui.path=/api/docs
springdoc.api-docs.path=/api/docs/json
springdoc.swagger-ui.operationsSorter=method

# Spring Cache
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=60m

# GitHub API
github.api.token=${GITHUB_TOKEN:}
github.api.base-url=https://api.github.com
github.api.username=yogeswaranv007

# Email Provider Configuration
email.provider=brevo

# Brevo HTTP API Configuration
brevo.api.key=${BREVO_API_KEY:}
brevo.email.admin=${ADMIN_EMAIL:}
brevo.email.from=${FROM_EMAIL:}
brevo.api.url=https://api.brevo.com/v3/smtp/email
