server.port=8080

# GitHub API Settings
github.api.token=${GITHUB_TOKEN:}
github.api.base-url=https://api.github.com
github.api.username=yogeswaranv007

# Swagger UI / OpenAPI
springdoc.swagger-ui.path=/api/docs
springdoc.api-docs.path=/api/docs/json
springdoc.swagger-ui.operationsSorter=method

# Spring Cache (Caffeine default settings can be overwritten in CacheConfig)
spring.cache.type=caffeine
